Models/Licence.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace lindaniDS.Models
{
    public class Licence
    {
        [Key]
        public int LearnerID { get; set; }

        public string Names { get; set; }
        public string Email { get; set; }

        //[ForeignKey("User")]
        //public int UserID { get; set; }
        //public virtual User User { get; set; }

        //[ForeignKey("BookingPackages")]
        //public int PackageID { get; set; }
        //public virtual BookingPackages BookingPackages { get; set; }

        [StringLength(50, ErrorMessage = "Please provide with valid E-mail!")]
        [Display(Name = "Province")]
        public string Province { get; set; }

        [StringLength(50, ErrorMessage = "Please provide with valid E-mail!")]
        [Display(Name = "City")]
        public string City { get; set; }

        [StringLength(50, ErrorMessage = "Please provide with valid E-mail!")]
        [Display(Name = "Surbub")]
        public string Surbub { get; set; }

        [StringLength(50, ErrorMessage = "Please provide with valid E-mail!")]
        [Display(Name = "Street")]
        public string Street { get; set; }

        [Display(Name = "Zip Code")]
        public int ZipCode { get; set; }
        public ulong Phone { get; set; }
        public ulong IDNum { get; set; }
        public string Location { get; set; }
        public DateTime BookingDate { get; set; }
        public DateTime BookingDate2 { get; set; }
        // public string Photo { get; set; }
        public string Picture { get; set; }
        public int Code { get; set; }
    }
}

Controllers/LicencesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using lindaniDS.Models;
using System.Net.Mail;

namespace lindaniDS.Controllers
{
    public class LicencesController : Controller
    {
        private LindaniContext db = new LindaniContext();

        // GET: Licences
        public async Task<ActionResult> Index()
        {
           // ViewBag.userId = User.Identity.GetUserId();
            var licences = db.Licences;
            return View(await licences.ToListAsync());
        }

        public async Task<ActionResult> myBookings(string email)
        {
            // ViewBag.userId = User.Identity.GetUserId();
            var licences = db.Licences.Where(a => a.Email == email);
            return View(await licences.ToListAsync());
        }
        public async Task<ActionResult> AdminView()
        {
            // ViewBag.userId = User.Identity.GetUserId();
            var licences = db.Licences;
            return View(await licences.ToListAsync());
        }

        // GET: Licences/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Licence licence = await db.Licences.FindAsync(id);
            if (licence == null)
            {
                return HttpNotFound();
            }
            return View(licence);
        }

        // GET: Licences/Create
        public ActionResult Create()
        {
           // ViewBag.PackageID = new SelectList(db.BookingPackages, "PackageID", "Name");
           // ViewBag.UserID = new SelectList(db.Users, "UserID", "FirstName");
            return View();
        }

        // POST: Licences/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "LearnerID,UserID,Names,Email,Province,City,Surbub,Street,ZipCode,Phone,IDNum,Location,BookingDate,BookingDate2,Photo,Picture,Code")] Licence licence, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    /// Mail ///                    
                    string subject = "Your booking for Code "+licence.Code+" Licence was successfull";

                    string message = "This message was sent to "+licence.Names+" ' " +licence.Email+ " ' \n " +
                        "If it is not yours just ignore or contact us on amocodes@gmail.com \n \n " +
                        "Hello you booked code "+licence.Code+" Licence. Your Sessions and Lessons will take place from "+licence.BookingDate+" untill "+licence.BookingDate2+"." +
                        "\n \n We will be happy to meet you in "+licence.Location+" at "+licence.BookingDate+"\n \n " +
                        "We hank you \n Lindani DS \n";

                    /////./Mail ///
                    string _FileName = Path.GetFileName(upload.FileName);
                    string _path = Path.Combine(Server.MapPath("~/Images"), _FileName);
                    upload.SaveAs(_path);
                    licence.Picture = _FileName;
                    /// mail
                    System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;
                    MailAddress to = new MailAddress(licence.Email);
                    MailAddress from = new MailAddress("amocodes@gmail.com");

                    MailMessage mm = new MailMessage(from, to);
                    mm.Subject = subject;
                    mm.Body =  message;
                    mm.IsBodyHtml = false;

                    SmtpClient smtp = new SmtpClient();
                    smtp.Host = "smtp.gmail.com";
                    smtp.Port = 587;
                    smtp.EnableSsl = true;

                    NetworkCredential nc = new NetworkCredential("amocodes@gmail.com", "@Dut991110");
                    smtp.UseDefaultCredentials = false;
                    smtp.Credentials = nc;
                    smtp.Send(mm);

                   // licence.BookingDate2 = licence.BookingDate;
                    db.Licences.Add(licence);
                    await db.SaveChangesAsync();
                    return RedirectToAction("ThankBooking", "Home");
                }
                /// licence.LearnerID = Session[""]
                return View(licence);
            }

           // ViewBag.PackageID = new SelectList(db.BookingPackages, "PackageID", "Name", licence.PackageID);
           // ViewBag.UserID = new SelectList(db.Users, "UserID", "FirstName", licence.UserID);
            return View(licence);
        }

        // GET: Licences/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Licence licence = await db.Licences.FindAsync(id);
            if (licence == null)
            {
                return HttpNotFound();
            }
           // ViewBag.PackageID = new SelectList(db.BookingPackages, "PackageID", "Name", licence.PackageID);
           // ViewBag.UserID = new SelectList(db.Users, "UserID", "FirstName", licence.UserID);
            return View(licence);
        }

        // POST: Licences/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "LearnerID,Province,City,Surbub,Street,ZipCode,Phone,IDNum,Location,BookingDate,Photo,Picture,Code")] Licence licence)
        {
            if (ModelState.IsValid)
            {
                db.Entry(licence).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
           // ViewBag.PackageID = new SelectList(db.BookingPackages, "PackageID", "Name", licence.PackageID);
          //  ViewBag.UserID = new SelectList(db.Users, "UserID", "FirstName", licence.UserID);
            return View(licence);
        }

        // GET: Licences/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Licence licence = await db.Licences.FindAsync(id);
            if (licence == null)
            {
                return HttpNotFound();
            }
            return View(licence);
        }

        // POST: Licences/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Licence licence = await db.Licences.FindAsync(id);
            db.Licences.Remove(licence);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Licences/AdminView.cshtml
@model IEnumerable<lindaniDS.Models.Licence>

@{
    ViewBag.Title = "AdminView";
   Layout = "~/Views/Shared/_Admin.cshtml";
}
<div class="row py-4">
    <div class="col-12 h4 font-weight-bold text-center ">
        All The Licences Bookings
    </div>
</div>
<hr />
<table class="table bg-white rounded">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Names)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Province)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Surbub)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Street)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ZipCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IDNum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BookingDate)
        </th>
     
        <th>
            @Html.DisplayNameFor(model => model.Picture)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Code)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Names)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Province)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surbub)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Street)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ZipCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IDNum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BookingDate)
            </td>
          
            <td>
                @Html.DisplayFor(modelItem => item.Picture)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.LearnerID }) |
                @Html.ActionLink("Details", "Details", new { id = item.LearnerID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.LearnerID })
            </td>
        </tr>
    }

</table>

Views/Licences/Create.cshtml
@model lindaniDS.Models.Licence

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="row mx-5 mb-3 mt-5">
    <div class="col-md-4">
        @Html.ActionLink("Back to List", "Index")
    </div>
    <div class="col-md-7 h4">
        Book For Licence
    </div>
</div>
<hr />

@using (Html.BeginForm("Create", "Licences", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="row mx-5 mt-5">
        <div class="col-md-4 ml-5">

            @*<div class="md-form md-outline">
                    @Html.LabelFor(model => model.UserID, "UserID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control  form-control-sm validate" })
                        @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="md-form md-outline">
                    @Html.LabelFor(model => model.PackageID, "PackageID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("PackageID", null, htmlAttributes: new { @class = "form-control  form-control-sm validate" })
                        @Html.ValidationMessageFor(model => model.PackageID, "", new { @class = "text-danger" })
                    </div>
                </div>*@



            <div class="form-group">

                <textarea class="form-control rounded-0 border-0" id="exampleFormControlTextarea2" rows="1" disabled>Provide us with your details so that we can send and Update you on your Booking</textarea>
            </div>

            <div class="md-form md-outline">
                <input type="text" id="Name" name="Name" class="form-control  form-control-sm validate" />
                <label for="Name" data-error="wrong" data-success="right">Names</label>
            </div>

            <div class="md-form md-outline">
                <input type="text" id="Email" name="Email" value="@ViewBag.email" class="form-control  form-control-sm validate" />
                <label for="Email" data-error="wrong" data-success="right">Email</label>
            </div>



            <div class="md-form md-outline">

                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control  form-control-sm validate" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                <label for="Phone" data-error="wrong" data-success="right">Phone Number</label>
            </div>

            <div class="md-form md-outline">

                @Html.EditorFor(model => model.IDNum, new { htmlAttributes = new { @class = "form-control  form-control-sm validate" } })
                @Html.ValidationMessageFor(model => model.IDNum, "", new { @class = "text-danger" })
                <label for="IDNum" data-error="wrong" data-success="right">ID Number</label>
            </div>

        </div>
        <div class="col-md-3">

            <div class="md-form md-outline">
                <input type="text" name="Province" id="province" class="form-control form-control-sm validate" />
                @Html.ValidationMessageFor(model => model.Province, "", new { @class = "text-danger" })
                <label for="province" data-error="wrong" data-success="right">Province</label>
            </div>



            <div class="md-form md-outline">

                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control form-control-sm validate" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                <label for="City" data-error="wrong" data-success="right">City</label>
            </div>

            <div class="md-form md-outline">
                <input type="text" id="Surbub" name="Surbub" class="form-control  form-control-sm validate" />
                <label for="Surbub" data-error="wrong" data-success="right">Surbub</label>
            </div>

            <div class="md-form md-outline">

                @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control  form-control-sm validate" } })
                @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
                <label for="Street" data-error="wrong" data-success="right">Street Address</label>
            </div>

            <div class="md-form md-outline">

                @Html.EditorFor(model => model.ZipCode, new { htmlAttributes = new { @class = "form-control  form-control-sm validate" } })
                @Html.ValidationMessageFor(model => model.ZipCode, "", new { @class = "text-danger" })
                <label for="ZipCode" data-error="wrong" data-success="right">Zip Code</label>
            </div>



        </div>
        <div class="col-md-4">
            <div class="md-form md-outline">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control  form-control-sm validate" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
                <label for="Location" data-error="wrong" data-success="right">Location</label>
            </div>

            <div id="date-picker-example" class="md-form md-outline input-with-post-icon datepicker">
                <input placeholder="Select date" type="date" name="BookingDate" id="BookingDate" class="form-control">
                <label for="BookingDate" data-error="wrong" data-success="right">Booking From</label>
            </div>

            <div id="date-picker-example" class="md-form md-outline input-with-post-icon datepicker">
                <input placeholder="Select date" type="date" name="BookingDate2" id="BookingDate2" class="form-control">

                <label for="BookingDate2" data-error="wrong" data-success="right">Booking To</label>

            </div>


            @*<div class="md-form md-outline">

            @Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control  form-control-sm validate" } })
            @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
            <label for="Photo" data-error="wrong" data-success="right">Photo</label>
        </div>*@
            <label for="upload" class="" data-error="wrong" data-success="right">Upload Learners</label>
            <div class="md-form md-outline file-field file-upload-wrapper" id="file" onclick="file()">
                <input type="file" name="upload" id="upload" class="form-control-file btn-floating peach-gradient mt-0 float-left" />
                @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger   form-control-sm validate" })
                <i class="fas fa-paperclip" aria-hidden="true"></i>
            </div>

            <label for="Code" class="mdb-main-label">Choose Licence Code</label> <br />
            <select class="browser-default custom-select" name="Code" id="Code" editable="true" searchable="Search and add here...">
                <option value="" disabled selected>Choose your option</option>
                <option value="08">Code 08</option>
                <option value="10">Code 10</option>
                <option value="14">Code 14</option>
            </select>




        </div>
    </div>
    <div class="row text-center">
        <div class="col-md-12 text-center">
            <input type="submit" value="Create" class="btn form btn-primary" />

        </div>
    </div>
}

<script>
    function con() {
        document.getElementById("file").addEventListener('click', function () {
         //   window.confirm("hello");
            //validation code to see State field is mandatory.  
        });
    }

    function file() {
        setTimeout(function () {
            window.confirm("Your document is in right format, Click ok to procced");
        }, 8000);
    }
   // setTimeout(con, 3000);
</script>

Views/Licences/Delete.cshtml
@model lindaniDS.Models.Licence

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Licence</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Names)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Names)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Province)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Province)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surbub)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surbub)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Street)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Street)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZipCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IDNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IDNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BookingDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookingDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Picture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Picture)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Licences/Details.cshtml
@model lindaniDS.Models.Licence

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Licence</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BookingPackages.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookingPackages.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Province)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Province)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surbub)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surbub)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Street)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Street)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZipCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IDNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IDNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BookingDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookingDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Picture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Picture)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.LearnerID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Licences/Index.cshtml
@model IEnumerable<lindaniDS.Models.Licence>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row mt-5">
    <div class="col-md-3">

    </div>
    <div class="col-md-6 text-center">
        <h2>Your Booking Details</h2>

    </div>
    <div class="col-md-3">

    </div>
</div>
<p>
    @Html.ActionLink("Add New Booking", "Create", new { area=""},new {@class = "btn btn-sm btn-info btn-outline-info"})
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Names)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Province)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Surbub)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Street)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ZipCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IDNum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BookingDate)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Photo)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.Picture)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Code)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Names)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Province)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Surbub)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Street)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ZipCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IDNum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Location)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BookingDate)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.Photo)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.Picture)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Code)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.LearnerID }) |
            @Html.ActionLink("Details", "Details", new { id=item.LearnerID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.LearnerID })
        </td>
    </tr>
}

</table>